version: '3.4'

networks:
  web:
  controlpanel:
  loadtesting:

services:
  # Two services in the same network ~ pod
  app: #web app main container
    build: DemoWeb/.
    networks:
      - web
    ports:
      - "1111:1111"
    volumes: # The runtime creates diagnostics server which binds to a Unix domain socket in this volume
      - "./dotnet-tmp:/tmp"  
  #sidecar container
  dotnet-monitor:
    image: mcr.microsoft.com/dotnet/monitor
    networks:
      - web
    ports:
      - "2222:52323"
    volumes:
      - "./dotnet-tmp:/tmp" #  dotnet-monitor communicates with the runtime via IPC using this socket.
    command:
      - "--urls http://*:52323"
      - "--no-auth"

  #Control panel "pod"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - controlpanel
  grafana:
    image: grafana/grafana:latest
    networks:
      - controlpanel
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/      
  
  #Load testing tool
  k6:
    image: loadimpact/k6:latest
    networks:
      - loadtesting
    ports:
      - "6565:6565"
    #environment:
    #  - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - "./k6:/scripts"
    command:
      - "run"
      - "/scripts/stress.js"
